### ISSUE TITLE
Error in plotting accuracy , keras

### ISSUE THREAD

**Issue by shintan777** [Auto-DL/DLMML#28]
File "test.py", line 27, in summarize_diagnostics
    pyplot.plot(history.history['accuracy'], color='blue', label='train')
KeyError: 'accuracy'

**Comment by ADI10HERO** [comment]
It's because of the Version of Keras and tensorflow on your machine

Please test it with the ones mentioned in requirements.txt and let me know if the error persists

**Comment by shintan777** [comment]
Yes @ADI10HERO  I tested with the correct version and it works.

**Comment by ADI10HERO** [comment]
Okay, awesome, so I'll be closing this issue then.

Feel free to reopen if you face any difficulties :D
